Feature: Homework 6
js53110/Sofascore2024 pull request #7
Opened 2024-05-08 07:22 UTC by js53110

LoadingViewController sam ostavio ako bude trebalo koristit, al sam pozive apia stavio u MainVC

Mislim da jos treba mijenjat helpers sto se tice onih statusa utakmica, zasad sam pokrio homewin, awaywin, draw i notstarted, jer nisam vidio kakvo je stanje odgovora kad je match in progress

Proba sam sto vise odvojit u svoje ekstenzije i postavit MARK

Ima dosta novog koda tako da sretno :D

2024-05-20 10:56 UTC, josipas requested changes
Dobra je zadaca, treba samo optimizirat i urediti kod i opcenito pripaziti na konzistentnost, bitno mi je da prodjes ovo za reload na MainVC i ovo sa slikama.

2024-05-20 10:56 UTC, josipas commented on SofascoreAcademy/SofascoreAcademy/Network/ApiClient.swift
> +enum NetworkError: Error {
zasto imas i network error i api error koji su ista stvar?

2024-05-20 10:56 UTC, josipas commented on SofascoreAcademy/SofascoreAcademy/Network/ApiClient.swift
> +    func getDataForSport(sportSlug: SportSlug, date: String) async -> Result<[Event], NetworkError> {
```suggestion
    func getData(for sportSlug: SportSlug, date: String) async -> Result<[Event], NetworkError> {
```

mozes ovako

2024-05-20 10:56 UTC, josipas commented on SofascoreAcademy/SofascoreAcademy/Protocols/DatePickDelegate.swift
> +protocol DatePickDelegate: AnyObject {
import Foundation gdje treba dodaj

2024-05-20 10:56 UTC, josipas commented on SofascoreAcademy/SofascoreAcademy/Protocols/LeagueLogoLoadProtocol.swift
> +protocol LeagueLogoLoadDelegate: AnyObject {
```suggestion
import UIKit

protocol LeagueLogoLoadDelegate: AnyObject {
```

2024-05-20 10:56 UTC, josipas commented on SofascoreAcademy/SofascoreAcademy/Protocols/LeagueLogoLoadProtocol.swift
> +protocol LeagueLogoLoadDelegate: AnyObject {
zasto uikit?

2024-05-20 10:56 UTC, josipas commented on SofascoreAcademy/SofascoreAcademy/Public/Cache.swift
> +    static let shared = ImageCache()
```suggestion
class ImageCache {

    static let shared = ImageCache()
```

2024-05-20 10:56 UTC, josipas commented on SofascoreAcademy/SofascoreAcademy/Public/Cache.swift
> +        return cache.object(forKey: key as NSString)
ne treba return

2024-05-20 10:56 UTC, josipas commented on SofascoreAcademy/SofascoreAcademy/Public/Cache.swift
> +    func setImage(_ image: UIImage, forKey key: String) {
mogu se fje zvati set i get ili setimage i getimage

2024-05-20 10:56 UTC, josipas commented on SofascoreAcademy/SofascoreAcademy/Public/Styling.swift
> +//ovo sam kopirao sa zeplina, ali mi neki fontovi ne rade pa sam ostavio i ovo i moj Enum gore :/
koji fontovi ti ne rade?

2024-05-20 10:56 UTC, josipas commented on SofascoreAcademy/SofascoreAcademy/Views/CustomScrollView.swift
> +    func configureScrollView() {
bolji naming mozda

2024-05-20 10:56 UTC, josipas commented on SofascoreAcademy/SofascoreAcademy/Views/DatePickerCollectionView.swift
> +        //MARK: Assigning delegates
ne treba tu mark, to stavljamo za ekstenzije

2024-05-20 10:56 UTC, josipas commented on SofascoreAcademy/SofascoreAcademy/Views/DatePickerCollectionView.swift
> +        return 15
zasto je ovo hardkodirano?

2024-05-20 10:56 UTC, josipas commented on SofascoreAcademy/SofascoreAcademy/Views/DatePickerCollectionView.swift
> +        return 15
ps ne treba return

2024-05-20 10:56 UTC, josipas commented on SofascoreAcademy/SofascoreAcademy/Views/DateViewCell.swift
> +    static let identifier = "DateCell"
Nice!

2024-05-20 10:56 UTC, josipas commented on SofascoreAcademy/SofascoreAcademy/Views/DateViewCell.swift
> +    private var dayOfWeek = ""
Mogao si i ovako
```suggestion
    private var dayOfWeek: String?
```

2024-05-20 10:56 UTC, josipas commented on SofascoreAcademy/SofascoreAcademy/Views/MainViewController.swift
> +var selectedDate: String = Helpers.getTodaysDate()
Jel se moglo ovo napravit kao varijabla view controller-a pa da to saljes u collectionview?

2024-05-20 10:56 UTC, josipas commented on SofascoreAcademy/SofascoreAcademy/Views/MainViewController.swift
>  class MainViewController: UIViewController {
Trebalo mi je malo da se snadjem i predlozila bih mali refactor. Ovdje koliko shvacam ti trenutno kad odaberes datum spremis odmah sve evente za sva tri sporta za taj dan? Malo se cini redundantno ako je netko dosao u app samo gledat nogomet da mu loadas i za kosarku i za am nogomet.
Prijedlog:
U metodi displaySelectedSport spremas novoodabrani sport, a u metodi displayEventsForSelectedDate spremas novoodabrani datum. Obe metodu bi nakon tog spremanja mogle pozvat neku novu metodu reloadData() koja bi ti loadala samo potrebne podatke za trenutno odabrani sport i trenutno odabrani datum. Ta metoda isto moze biti async pa da ti tek nakon sto dobijes podatke promjenis sto treba, dakle ili samo updates sportvc s novim podacima za drugi datum u displayEventsForSelectedDate  ili trebas mijenjat sport u displaySelectedSport.
Prodji detaljno pa javi ako zapnes

2024-05-20 10:56 UTC, josipas commented on SofascoreAcademy/SofascoreAcademy/Views/DatesMatchesDividerView.swift
> +    override func setupConstraints() {
mozes koristiti inset kad imas equalToSuperview

2024-05-20 10:56 UTC, josipas commented on SofascoreAcademy/SofascoreAcademy/Views/DatesMatchesDividerView.swift
> +        dayLabel.snp.makeConstraints() {
Ova labela nema trailing, labele bi uvijek trebalu ograniciti u slucaju da dodje neki dugi tekst da ne podivlja

2024-05-20 10:56 UTC, josipas commented on SofascoreAcademy/SofascoreAcademy/Views/DatesMatchesDividerView.swift
> +        eventsCountLabel.snp.makeConstraints() {
nema leading, isti komentar kao i gore

2024-05-20 10:56 UTC, josipas commented on SofascoreAcademy/SofascoreAcademy/Views/DatesMatchesDividerView.swift
> +    override func setupConstraints() {
sad vidim da malo inset malo offset koristis 🙈

2024-05-20 10:56 UTC, josipas commented on SofascoreAcademy/SofascoreAcademy/Network/ApiClient.swift
> +    func getLeagueLogoApi(tournamentId: Int) async -> Result<UIImage, NetworkError> {
Shvacam motivaciju da je ovaj dio sa slikama ovdje. Medjutim, ono sto mozes napraviti je da izdvojis sve vezano uz slike u nekakav ImageService koji ce od ApiClienta dobivat baseUrl -> ovo je bitno jer ako mijenjas baseUrl da ga mijenjas samo na jednom mjestu a ne na sto mjesta po aplikaciji.
Dodatno, onda ne moras opterecivati vc s dohvatom slika nego ce view-ovi direkt svaki za sebe dohvacati slike. Tu je bitno naglasiti da view dobiva od ImageService-a samo UIImage, ImageService bi trebao odraditi taj dio provjere je li u cache-u, ako je vrati tu iz cache-a, ako nije obavi api poziv i ako je uspjesno dohvacena slika cacheiraj ju i vrati opet samo UIImage, sad hoces li vracati neki placeholder UIIImage ili nil u slucaju neuspjeha to je na requirementu zadatka. Takodjer, ovo detaljno prodji pa se javi ako zapnes.

2024-05-20 13:51 UTC, js53110 commented on SofascoreAcademy/SofascoreAcademy/Network/ApiClient.swift
> +enum NetworkError: Error {
Vjerojatno ostao pri merganju, maknem

2024-05-20 14:06 UTC, js53110 commented on SofascoreAcademy/SofascoreAcademy/Public/Styling.swift
> +//ovo sam kopirao sa zeplina, ali mi neki fontovi ne rade pa sam ostavio i ovo i moj Enum gore :/
Mislim da je ovaj CondensedRegular

2024-05-20 14:11 UTC, js53110 commented on SofascoreAcademy/SofascoreAcademy/Views/DatePickerCollectionView.swift
> +        return 15
jer prikazujem 15 dana, 7 dana unaprijed, 7 dana unazad i today?

2024-05-24 07:40 UTC, josipas requested changes
Pohvale za slike, prodji po komentarima, ali fokus na ovaj load podataka u MainVC

2024-05-24 07:40 UTC, josipas commented on SofascoreAcademy/SofascoreAcademy/Views/MainViewController.swift
> +var firstStart: Bool = true
ovo mozes prebacit kao varijablu u datepicker koja ce biti true te ces ju nakon toga prebacit u false, ili mozes rjesit putem user defaults-a

2024-05-24 07:40 UTC, josipas commented on SofascoreAcademy/SofascoreAcademy/Views/MainViewController.swift
> +        startLoading()
ovo prebaci u reload fju

2024-05-24 07:40 UTC, josipas commented on SofascoreAcademy/SofascoreAcademy/Views/MainViewController.swift
> +        reloadData(selectedDate: selectedDate, selectedSport: currentSportSlug)
Malo me muci ovaj naming reloadData i moze biti misleading. Prvi put kad se load-a, to zapravo nije reload nego load. Mozes napraviti load i reload fju i onda da reload zove load

2024-05-24 07:40 UTC, josipas commented on SofascoreAcademy/SofascoreAcademy/Public/Data.swift
> +var footballData: [LeagueData] = []
Ovo treba jos popraviti jer ima vise problema tu. Na losem je mjestu i sad kad vise ne ucitavas za sva tri sporta odjednom ti ne trebaju tri razl varijable za tri razl sporta. Trebao bi u MainVC staviti var sportData: [LeagueData] koju ces onda proslijedivati SportVC

2024-05-24 07:40 UTC, josipas commented on SofascoreAcademy/SofascoreAcademy/Public/Helpers.swift
> +    static func determineDataForDisplay(sportSlug : SportSlug) -> Array<LeagueData> {
nastavno na komentar o sportData, ovo ces moci maknuti

2024-05-24 07:40 UTC, josipas commented on SofascoreAcademy/SofascoreAcademy/Views/DatePickerCollectionView.swift
> +        return 15
Jasno, ali vise je isao komentar u smjeru da nije hardkodirano 15 jer ces morat rucno mijenjat ako dode zahtjev da se prikazuju 4 tjedna, a ne 2

2024-05-24 07:40 UTC, josipas commented on SofascoreAcademy/SofascoreAcademy/Views/DatePickerCollectionView.swift
> +            let dataForCell = Helpers.getDataForDateCell(index: indexPath.row)
Dodatno, bilo bi bolje da se ne zove odavde Helpers nego da ti podaci dolaze iz VC

2024-05-24 07:40 UTC, josipas commented on SofascoreAcademy/SofascoreAcademy/Network/ImageService.swift
> +        return UIImage()
samo da naglasim da u slucaju da imas neki placeholder to bi ovdje slao

2024-05-24 07:40 UTC, josipas commented on SofascoreAcademy/SofascoreAcademy/Network/ImageService.swift
> +class ImageService {
Ovo si jako lijepo napravio 🥳

2024-05-24 08:03 UTC, josipas commented
Dodatno, mozes za sljd zadacu ili za projekt, ali malo dodati foldere u projekt jer se sad vec malo tesko za snaci. Views da malo rasporedis po ekranima ili tako nesto

2024-05-27 16:58 UTC, josipas approved these changes

2024-05-27 16:58 UTC, josipas commented on SofascoreAcademy/SofascoreAcademy/Views/SportViewController.swift
> +                leagueLogo: UIImage()
ova slika ne triba uopce

2024-05-27 17:02 UTC, merged